
site_name: Fabula
theme:
  name: material
  custom_dir: 'yaml-wiki/theme'
  palette:
    primary: blue
    accent: blue
  favicon: 'img/favicon.ico'
  icon:
    logo: 'material/bank'
repo_name: 'tapanther/Fabula'
repo_url: 'https://github.com/tapanther/Fabula'
site_url: 'https://tapanther.github.io/Fabula/'





markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.superfences :
      custom_fences :
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

nav:
  - Home : index.md
  - General :
    - Bearer Marks : Marks.md
    - Timeline : Timeline.md
  - Major Powers :
    - Basileia of Aroth :
      - Basileia of Aroth : Aroth.md
    - The Commonwealth :
      - The Commonwealth : Commonwealth.md
  - NPC :
    - Basileia of Aroth :
      - Aurica Cinca : Aurica.md
      - Gratian Constantinus : Gratian.md
      - Mil Wulfa : Wulfa.md
    - The Commonwealth :
      - Eudoxia Duca : Duca.md
      - Goga Tsitsishvili : Tsitsishvili.md
      - Goga Tzatziki : Tzatziki.md
      - Mihaela Nicolae : Mihaela.md
      - Palaelogus Castinus : Castinus.md
      - Pivovarov Lavro : Pivovarov.md
  - Settlements :
    - Basileia of Aroth :
      - Pyrgeria : Pyrgeria.md
    - The Commonwealth :
      - Cythamahos : Cythamahos.md
      - Kamynthos : Kamynthos.md
      - Velia : Velia.md
  - Categories :
      - General : General.md
      - Major Powers : Major Powers.md
      - NPC : NPC.md
      - Settlements : Settlements.md
